---
# tasks file for hswong3i.postgresql

- name: include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags: hswong3i.postgresql

- name: apt-key add
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_key }}"
  notify: restart postgresql
  tags: hswong3i.postgresql

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_repository }}"
  notify: restart postgresql
  tags: hswong3i.postgresql

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt }}"
  notify: restart postgresql
  tags: hswong3i.postgresql

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/postgresql/9.5/main/pg_hba.conf.j2", dest: "/etc/postgresql/9.5/main/pg_hba.conf",  owner: "postgres", group: "postgres", mode: "0644" }
    - { src: "etc/postgresql/9.5/main/postgresql.conf.j2", dest: "/etc/postgresql/9.5/main/postgresql.conf",  owner: "postgres", group: "postgres", mode: "0644" }
  notify: restart postgresql
  tags: hswong3i.postgresql

- name: enable service
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: "postgresql", enabled: "yes" }
  notify: restart postgresql
  tags: hswong3i.postgresql
